
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action executeAction;
	private global::Gtk.Action cutAction;
	private global::Gtk.Action copyAction;
	private global::Gtk.Action pasteAction;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action gotoTopAction;
	private global::Gtk.Action gotoFirstAction;
	private global::Gtk.Action gotoLastAction;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action Action;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar_main;
	private global::Gtk.Toolbar toolbar_main;
	private global::Gtk.HBox hbox3;
	private global::Gtk.FileChooserWidget filechooserwidget1;
	private global::Gtk.Statusbar mainstatus;
	private global::Gtk.ComboBoxEntry dirnambox;
	private global::Gtk.ComboBoxEntry filefilterbox;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.executeAction = new global::Gtk.Action ("executeAction", null, null, "gtk-execute");
		w1.Add (this.executeAction, null);
		this.cutAction = new global::Gtk.Action ("cutAction", null, null, "gtk-cut");
		w1.Add (this.cutAction, null);
		this.copyAction = new global::Gtk.Action ("copyAction", null, null, "gtk-copy");
		w1.Add (this.copyAction, null);
		this.pasteAction = new global::Gtk.Action ("pasteAction", null, null, "gtk-paste");
		w1.Add (this.pasteAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.gotoTopAction = new global::Gtk.Action ("gotoTopAction", null, null, "gtk-goto-top");
		w1.Add (this.gotoTopAction, null);
		this.gotoFirstAction = new global::Gtk.Action ("gotoFirstAction", null, null, "gtk-goto-first");
		w1.Add (this.gotoFirstAction, null);
		this.gotoLastAction = new global::Gtk.Action ("gotoLastAction", null, null, "gtk-goto-last");
		w1.Add (this.gotoLastAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.Action = new global::Gtk.Action ("Action", null, null, null);
		w1.Add (this.Action, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar_main'><menu name='FileAction' action='FileAction'/><menu name='Action' action='Action'/></menubar></ui>");
		this.menubar_main = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar_main")));
		this.menubar_main.Name = "menubar_main";
		this.vbox1.Add (this.menubar_main);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar_main]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar_main'><toolitem name='executeAction' action='executeAction'/><toolitem name='cutAction' action='cutAction'/><toolitem name='copyAction' action='copyAction'/><toolitem name='pasteAction' action='pasteAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='gotoTopAction' action='gotoTopAction'/><toolitem name='gotoFirstAction' action='gotoFirstAction'/><toolitem name='gotoLastAction' action='gotoLastAction'/></toolbar></ui>");
		this.toolbar_main = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar_main")));
		this.toolbar_main.Name = "toolbar_main";
		this.toolbar_main.ShowArrow = false;
		this.vbox1.Add (this.toolbar_main);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar_main]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.filechooserwidget1 = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(0)));
		this.filechooserwidget1.Name = "filechooserwidget1";
		this.filechooserwidget1.LocalOnly = false;
		this.filechooserwidget1.SelectMultiple = true;
		this.hbox3.Add (this.filechooserwidget1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.filechooserwidget1]));
		w4.PackType = ((global::Gtk.PackType)(1));
		w4.Position = 0;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w5.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.mainstatus = new global::Gtk.Statusbar ();
		this.mainstatus.Name = "mainstatus";
		this.mainstatus.Spacing = 2;
		this.mainstatus.BorderWidth = ((uint)(2));
		// Container child mainstatus.Gtk.Box+BoxChild
		this.dirnambox = global::Gtk.ComboBoxEntry.NewText ();
		this.dirnambox.Name = "dirnambox";
		this.mainstatus.Add (this.dirnambox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.mainstatus [this.dirnambox]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child mainstatus.Gtk.Box+BoxChild
		this.filefilterbox = global::Gtk.ComboBoxEntry.NewText ();
		this.filefilterbox.Name = "filefilterbox";
		this.mainstatus.Add (this.filefilterbox);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.mainstatus [this.filefilterbox]));
		w7.Position = 2;
		this.vbox1.Add (this.mainstatus);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mainstatus]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 651;
		this.DefaultHeight = 550;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.filechooserwidget1.SelectionChanged += new global::System.EventHandler (this.OnFilechooserwidget1SelectionChanged);
		this.filechooserwidget1.FileActivated += new global::System.EventHandler (this.OnFilechooserwidget1FileActivated);
		this.filechooserwidget1.UpdatePreview += new global::System.EventHandler (this.OnFilechooserwidget1UpdatePreview);
		this.filechooserwidget1.CurrentFolderChanged += new global::System.EventHandler (this.OnFilechooserwidget1CurrentFolderChanged);
		this.filechooserwidget1.ConfirmOverwrite += new global::Gtk.ConfirmOverwriteHandler (this.OnFilechooserwidget1ConfirmOverwrite);
	}
}
